### PR TITLE
Enable line-length and document-start checks. Fix found issues.

### PR DESCRIPTION
**Pull request by vcrhonek**

### CODE REVIEW

**Comment by pcahyna** [comment]
we should reconsider enabling the document-start check. See https://github.com/oasis-roles/meta_standards#yaml-syntax

**Comment by richm** [comment]
I would like to close this PR in favor of https://github.com/linux-system-roles/kdump/pull/35

**Comment by vcrhonek** [comment]
@richm Sure, go ahead. Thanks!

**Comment by richm** [comment]
closed in favor of #35

**Pull request closed without merging**
