### PR TITLE
Rename 'dump_target.kind' to 'type' in conf template.

### PR DESCRIPTION
**Pull request by vcrhonek**

### CODE REVIEW

**Comment by vcrhonek** [comment]
I've noticed it thanks to failing 'tests/tests_ssh.yml'.

**Comment by pcahyna** [comment]
I see. This test did not exist yet in PR #5, that's why the CI passed for that PR.

**Comment by pcahyna** [comment]
That's not the reason. Even the master branch tests pass. It seems that the test needs `/sys/kernel/kexec_crash_size` to be nonzero. How did you achieve that?

**Comment by tyll** [comment]
> That's not the reason. Even the master branch tests pass. It seems that the test needs `/sys/kernel/kexec_crash_size` to be nonzero. How did you achieve that?

For the AnsibleFest demo I added crashkernel=128M to the kernel commandline (in grub.cfg) to achieve this IIRC.

**Comment by pcahyna** [comment]
> For the AnsibleFest demo I added crashkernel=128M to the kernel commandline (in grub.cfg) to achieve this IIRC.

IMO the role should do that automatically. I would expect it to configure kdump including all these low-level details.

**Comment by pcahyna** [comment]
[citest commit:a515518bb029cdf67d757f7f20a284c49a4eaff6]

**Comment by pcahyna** [comment]
@tyll when I set my membership to public, the CI started running. Cf. https://github.com/linux-system-roles/selinux/pull/33#issuecomment-427080228

**Comment by tyll** [comment]
> > For the AnsibleFest demo I added crashkernel=128M to the kernel commandline (in grub.cfg) to achieve this IIRC.
> 
> IMO the role should do that automatically. I would expect it to configure kdump including all these low-level details.

According to https://github.com/linux-system-roles/kdump/issues/6#issuecomment-299636928 VMs need to have enough RAM for the kernel to allocate space for kdump automatically. Therefore setting a specific size in the role is probably wrong. Instead the role should fail if kdump would not work IMHO and ask the user for a decision. There could also be an optional parameter to change this setting but handling the kernel commandline correctly in an automatic way is also tricky.

**Comment by pcahyna** [comment]
[citest pending]

**Comment by pcahyna** [comment]
[citest]

**Pull request merged**
