### PR TITLE
Avoid bare variable in when and the resulting warning.

### PR DESCRIPTION
**Pull request by pcahyna**

### CODE REVIEW

**Comment by richm** [comment]
can this be merged?  lgtm

**Comment by pcahyna** [comment]
In principle yes. Testing is insufficient though. It is no accident that all the rhel-8 tests fail. This is because the role is actually broken, but on systems other than rhel-8 it does not do anything, so the test seem to pass (if it did something, tests would break on those systems as well). This is fixed in #22, but it has its own problems with testing.

**Comment by richm** [comment]
> In principle yes. Testing is insufficient though. It is no accident that all the rhel-8 tests fail. This is because the role is actually broken, but on systems other than rhel-8 it does not do anything, so the test seem to pass (if it did something, tests would break on those systems as well). This is fixed in #22, but it has its own problems with testing.

What is the plan for merging this PR and #22?

**Comment by richm** [comment]
Can we merge this?  looks like a good bug fix

**Comment by jharuda** [comment]
[citest bad]

**Comment by richm** [comment]
@pcahyna please rebase and repush so we can get test coverage with tox and the latest integration test CI platforms

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Comment by pcahyna** [comment]
@richm rebased and updated - one can simplify the fix using Ansible 2.8 features (`default` on attributes of an undefined dict is now allowed).

**Review by richm — APPROVED** [review]
lgtm

**Comment by richm** [comment]
@pcahyna @spetrosi we're getting centos-6 failures but not rhel-6 failures?

**Comment by pcahyna** [comment]
> @pcahyna @spetrosi we're getting centos-6 failures but not rhel-6 failures?

On RHEL 6 the relevant tasks are silently skipped (by a condition for /sys/kernel/kexec_crash_size)

**Comment by richm** [comment]
> > @pcahyna @spetrosi we're getting centos-6 failures but not rhel-6 failures?
> 
> On RHEL 6 the relevant tasks are silently skipped (by a condition for /sys/kernel/kexec_crash_size)

ok - following the conversation athttps://github.com/linux-system-roles/kdump/pull/76#issuecomment-802005011 - the tests need to hack /sbin/mkdumprd ?  @spetrosi do you have a commit which does this?

**Comment by pcahyna** [comment]
> > > @pcahyna @spetrosi we're getting centos-6 failures but not rhel-6 failures?
> > 
> > 
> > On RHEL 6 the relevant tasks are silently skipped (by a condition for /sys/kernel/kexec_crash_size)
> 
> ok - following the conversation at [#76 (comment)](https://github.com/linux-system-roles/kdump/pull/76#issuecomment-802005011) - the tests need to hack /sbin/mkdumprd ? @spetrosi do you have a commit which does this?

No, for the problem where the role gets skipped on RHEL 6 and the tests succeed where they should not , it is apparently needed to reboot the machine: https://github.com/linux-system-roles/kdump/commit/8e7cf221f00b98d422cc6e28fda5f080717ab57d https://github.com/linux-system-roles/kdump/pull/76#issuecomment-801995567

(This is an actual problem of the role which could occur on user machines, not just in the test, so it should be fixed.)

For the problem that happens on CentOS 6 and would happen also on RHEL 6 when the above gets fixed, I am not sure. It would be "fixed" by hacking `/sbin/mkdumprd`, but this does not sound like a good approach.

**Comment by spetrosi** [comment]
The problem occurs because the rests try to ssh into themselves  - and this is not something that mkdumprd expects. Users might face such an issue in a real world, but not very likely.

**Comment by richm** [comment]
> The problem occurs because the rests try to ssh into themselves - and this is not something that mkdumprd expects. Users might face such an issue in a real world, but not very likely.

ok - so how can we cover this test on el6?  Do we need to skip this test on el6?

**Comment by pcahyna** [comment]
> > The problem occurs because the rests try to ssh into themselves - and this is not something that mkdumprd expects. Users might face such an issue in a real world, but not very likely.
> 
> ok - so how can we cover this test on el6? Do we need to skip this test on el6?

Let's separate the issue for upstream and downstream.

For downstream, using the control host as the kdump server has actually worked fine. So I can return to the original version of test in #22 (it used the control host as the kdump server) conditionally (when the control host supports it). The test will get a bit more complicated, because it will need to check whether the control host supports this mode and adjust its behavior accordingly, but it is still better than changing a file in the managed system which has never been intended to be changed this way. This solves the issue properly, because it is similar to how the code will be used in practice.

For upstream, I don't know. We could just skip the test on RHEL6 in case when using the control host is not allowed. The ideal solution would be to have a multihost capability in the CI.

**Comment by pcahyna** [comment]
Anyway, I can merge the PR now, ok?

**Comment by richm** [comment]
> Anyway, I can merge the PR now, ok?

yes, sorry for the distraction

**Pull request merged**
