### PR TITLE
update tox-lsr version to 2.8.0

### PR DESCRIPTION
**Pull request by spetrosi**
New version adds check for proper commenting of the ansible_managed var

### CODE REVIEW

**Comment by richm** [comment]
Is the intention to have a subsequent change to .github/workflows/tox.yml to add the test to check for the comments?  Something like
```
          39) toxenvs="${toxenvs},coveralls,ansible-managed-var-comment" ;;
```
Otherwise, this commit needs to both change the version of tox-lsr to 2.8.0, and add the check

**Comment by spetrosi** [comment]
In the case when the incorrect commenting is found, the test fails as expected.

**Comment by spetrosi** [comment]
> Is the intention to have a subsequent change to .github/workflows/tox.yml to add the test to check for the comments? Something like
> 
> ```
>           39) toxenvs="${toxenvs},coveralls,ansible-managed-var-comment" ;;
> ```
> 
> Otherwise, this commit needs to both change the version of tox-lsr to 2.8.0, and add the check

Completely forgot about this. Fixed now everywhere. For roles which PRs have been merged, I've opened new PRs.

**Review by richm — APPROVED** [review]
lgtm

**Pull request merged**
