### PR TITLE
Test if the ansible-managed-var-comment check works

### PR DESCRIPTION
**Pull request by spetrosi**

### CODE REVIEW

**Comment by richm** [comment]
with the new tox-lsr changes, I had to move some checks from py36 to py38 - see https://github.com/linux-system-roles/kdump/pull/91

**Comment by spetrosi** [comment]
@richm can you help me troubleshoot why tox does not complain about that I introduced` # {{ ansible_managed }}`? See the check here: https://github.com/linux-system-roles/tox-lsr/pull/44/files.
In the check, I grep in the current directory `.`, is this correct? The command works for me locally and exits with `1`.

**Comment by richm** [comment]
> @richm can you help me troubleshoot why tox does not complain about that I introduced` # {{ ansible_managed }}`? See the check here: https://github.com/linux-system-roles/tox-lsr/pull/44/files. In the check, I grep in the current directory `.`, is this correct? The command works for me locally and exits with `1`.

you need to add it to .github/workflows/tox.yml - it must be explicitly specified - I added it

**Comment by richm** [comment]
Another problem is that you are using bash constructs such as `&&`, `||`, and `exit` - the tox `commands` processor uses the equivalent of subprocess.run - so if you want to do a multiline bash "script", you'll need to do something like this: https://github.com/linux-system-roles/tox-lsr/blob/403af64f983485a3eedc77a824ef28eaebcf2ce5/src/tox_lsr/config_files/tox-default.ini#L42-L47

**Pull request closed without merging**
